### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by fgrande** [theomessin/laravel-devcontainer#1]
Hi,
may I ask You what to do next ? 

I have Docker installed.
I have Remote Containers installed on VStudioCode

Could You please integrate Your README file with some info about installing Laravel ? 

Tks
FabioG

**Comment by theomessin** [comment]
Hi @fgrande. This repo assumes you've got Laravel ready to go. 
More info on how to install Laravel can be found here:
https://laravel.com/docs/7.x/installation

~~I might add some more info on how to use this devcontainer at some point in the future - this is just a repo for myself at the moment.~~

Repo has been updated and full instructions have now been added 😃
