### ISSUE TITLE
[question] connect to RDS instead local mysql?

### ISSUE THREAD

**Issue by hebertlima** [theomessin/laravel-devcontainer#5]
Hello there, first, thank you so much for this repo, 
it's amazing the way that works!

I wonder to know if it's possible to connect to the Amazon RDS database?
I'm trying to put the credentials to .env, but I got denied msg and the IP showing on error was not from my RDS address

**Comment by theomessin** [comment]
Hello, I don't see why not. There's nothing in the `devcontainer` preventing you from doing this.
If its not working it might have something to do with your config. Sorry I can't be more helpful
